const express = require('express');
const userRouter = require('./routes/user.routes');
const commentsRouter = require('./routes/comments.routes');
const gamesRouter = require('./routes/games.routes');
const gamesGenersRouter = require('./routes/gamesandgenres.routes');
const genresRouter = require('./routes/genres.routes');
const libraryRouter = require('./routes/library.routes');
const passwordLoginRouter = require('./routes/passwordandlogin.routes');
const publisherGamesRouter = require('./routes/publisher_and_games.routes');
const publisherRouter = require('./routes/publisher.routes');
const PORT = process.env.PORT || 8080;
const app = express();
app.use(express.json());
app.use('/api', userRouter);
app.use('/api', commentsRouter);
app.use('/api', gamesRouter);
app.use('/api', gamesGenersRouter);
app.use('/api', genresRouter);
app.use('/api', libraryRouter);
app.use('/api', passwordLoginRouter);
app.use('/api', publisherGamesRouter);
app.use('/api', publisherRouter);
app.listen(PORT, () => console.log(`Server started on port ${PORT}`));